---
title: "Schedule"
output:
 html_document:
   toc: true
   toc_depth: 5
   toc_float:
     collapsed: false
     smooth_scroll: false
---

# 2025

| Date      | Presenter  | Topic  | Software | Slides | Code | Resources  |                                         
|:----------|:----------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|:--------------:|:-----------------------:|:------------:|:-------------------:|
02/13/2025 12 -- 1pm | [Caroline Andy, MS](https://phs.weill.cornell.edu/directory/profiles/andy-caroline) | Causal inference methods for combining randomized trials and observational studies | `R` | | | |

# 2024

| Date      | Presenter  | Topic  | Software | Slides | Code | Resources  |                                         
|:----------|:----------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|:--------------:|:-----------------------:|:------------:|:-------------------:|
02/02/2024 3 -- 4pm | [Anjile An, MPH](https://phs.weill.cornell.edu/directory/profiles/anjile) | Incorporating design principles into scientific research | | | | |

# 2023

| Date      | Presenter  | Topic  | Software | Slides | Code | Resources  |                                         
|:----------|:----------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|:--------------:|:-----------------------:|:------------:|:-------------------:|
11/16/2023 1 -- 2pm | [Caroline Andy, MS](https://phs.weill.cornell.edu/directory/profiles/andy-caroline) <br> Yuqing Qiu, MS | Introduction to Meta-Analysis <br> Inverse Probability Weighting for Dealing with Missing Outcomes | `R` <br> `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2023/202311_Andy_Introduction_to_Meta_Analysis.pdf) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2023/202311_Qiu_IPW_Missing_Outcomes.pdf) | |
09/07/2023 12 -- 1pm | [Will Simmons, MPH](https://simmwill.github.io) | Timeseries using `fable`: modeling COVID-era pediatric mental health emergencies | `R` | [<i class="fas fa-desktop fa-lg"></i>](https://simmwill.github.io/pres-timeseries-peds-mh) | | |
08/04/2023 1 -- 2pm | Attendees of NY R Conference | Takeaways from the New York R Conference 2023 | `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2023/202308_An_Wu_NYR_time_series.pdf) [<i class="fas fa-desktop fa-lg"></i>](https://simmwill.github.io/pres-quarto-revealjs/#/creating-slides-with-quarto-and-reveal.js) | | [<i class="fab fa-safari fa-lg"></i>](https://www.caitlinhudon.com/posts/framework-decisions-data) [<i class="fab fa-safari fa-lg"></i>](https://jaredlander.com/content/2023/07/LLMPackage.html#/title-slide) |
04/14/2023 1 -- 2pm | Ying Li, MS <br> Brady Rippon, MS | Submitting your R package to CRAN <br> Setting up a workflow with RProjects | `R` <br> `R` | [<i class="fas fa-desktop fa-lg"></i>](https://yinglia.github.io/Submitting-your-package-to-CRAN) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2023/202304_Rippon_Workflow_with_RProjects.pdf) | <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2023/202304_Rippon_Workflow_with_RProjects_template.zip) | |
02/17/2023 1 -- 2pm | Bilal Shaikh, MS <br> Vasili Fokaidis, MS <br> [Anjile An, MPH](https://phs.weill.cornell.edu/directory/profiles/anjile) | Introduction to REDCap Cloud <br> Making shiny apps easier with `golem` <br> The `tidylog` lifestyle | `REDCap` <br> `R` <br> `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2023/202302_Shaikh_Randomization_REDCap.pdf) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2023/202302_Fokaidis_shinyapps_with_golem.pdf) | <br> <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2023/202302_An_tidylog_demo.R) | |


# 2022

| Date      | Presenter  | Topic  | Software | Slides | Code | Resources  |                                         
|:----------|:----------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|:--------------:|:-----------------------:|:------------:|:-------------------:|
10/04/2022 12 -- 1pm | Colby Lewis V, MS <br> Rachel Heise, MS | Like Riding a Bike: API Basics for Statisticians <br> Data diagnosis, exploration, and transformation with `dlookr` | `R` <br> `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2022/202210_Lewis_citibike_api.pdf) <br> [<i class="fas fa-desktop fa-lg"></i>](https://rachelheise.github.io/dlookr/dlookr_slides.html#1) | [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2022/202210_Lewis_citibike_api_code.Rmd)
09/06/2022 4 -- 5pm | [Katherine Hoffman, MS](https://www.khstats.com/about) <br> [Will Simmons, MPH](https://simmwill.github.io) | Swimmer plots in R <br> Getting Organized with Notion | `R` <br> `R` | [<i class="fas fa-desktop fa-lg"></i>](https://kathoffman.github.io/swimmer-plots/slides-wcm.html#1) <br> [<i class="fas fa-desktop fa-lg"></i>](https://simmwill.github.io/notion-pres.html) | [<i class="fa fa-file-code-o fa-lg"></i>](https://github.com/kathoffman/swimmer-plots/blob/master/slides-wcm.Rmd) <br> [<i class="fa fa-file-code-o fa-lg"></i>](bit.ly/wcmbcc-notion) | [<i class="fab fa-safari fa-lg"></i>](https://www.khstats.com/blog/trt-timelines/multiple-vars/) [<i class="fab fa-safari fa-lg"></i>](https://www.khstats.com/blog/trt-timelines/trt-timelines/)
08/02/2022 4 -- 5pm | Brady Rippon, MS <br> <br> [Anjile An, MPH](https://phs.weill.cornell.edu/directory/profiles/anjile) | Becoming an AnimatoR: applications in `ggplot`, `gganimate`, and more <br> LEGO fun with `brickr` | `R` <br> <br> `R` | [<i class="fas fa-desktop fa-lg"></i>](https://rpubs.com/bradyrippon/929572) <br> <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2022/202208_An_brickr.pdf) | <br> <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2022/202208_An_brickr.zip) | |
| 06/23/2022 4 -- 5pm | [Katherine Hoffman, MS](https://www.khstats.com) <br> Diego Salazar, PhD <br> [Will Simmons, MPH](https://simmwill.github.io) <br> [Jacky Choi, MPH](https://phs.weill.cornell.edu/directory/profiles/jacky-choi) <br> Vasilios Fokaidis, MS | Tips and Tricks for Table 1's <br> A Shiny App for TMLE <br> `dbplyr` and the tidy-SQL-verse <br> Effect size plots using `ggplot2` <br> Say Hello to `highcharter` | `R` <br> `R` <br> `R` <br> `R` <br> `R`| [<i class="fas fa-desktop fa-lg"></i>](file_slides/2022/202206_Hoffman_Tips_Tricks_for_Table1.pdf) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2022/202206_Salazar_ShinyTMLE.pdf) <br> [<i class="fas fa-desktop fa-lg"></i>](https://docs.google.com/presentation/d/1cWrmY1kkvNqVgjiJAQoiykHSPzLbkeybxk-2LEePH6Q/edit#slide=id.p)<br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2022/202206_Choi_Effect_Size_Plots.pdf) <br>  [<i class="fas fa-desktop fa-lg"></i>](file_slides/2022/202206_Fokaidis_uber_highcharter.html) [<i class="fas fa-desktop fa-lg"></i>](file_slides/2022/202206_Fokaidis_Highcharter.pdf)  | <br> [<i class="fa fa-file-code-o fa-lg"></i>](https://github.com/dasalazarb/tmleShiny)<br> <br> <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2022/202206_Fokaidis_uber_highcharter.Rmd)  |

# 2021

| Date      | Presenter  | Topic  | Software | Slides | Code | Resources  |                                         
|:----------|:----------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|:--------------:|:-----------------------:|:------------:|:-------------------:|
| 09/13/2021 12 -- 1pm | [Anjile An, MPH](https://phs.weill.cornell.edu/directory/profiles/anjile) <br> Victoria Cooley, MS | Geospatial Analysis in R <br> Alluvial Plots with `ggalluvial` | `R` <br> `R`|[<i class="fas fa-play fa-lg"></i>](https://wcm.box.com/s/zi4uh9pruxaeppok8vnirn1j5pkmuxld) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2021/202109_Cooley_Alluvial.html) | [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2021/202109_An_Geospatial_Analysis.zip) <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2021/202109_Cooley_Alluvial.Rmd)
| 06/29/2021 12 -- 1pm | [Will Simmons, MPH](https://simmwill.github.io) <br> [Jacky Choi, MPH](https://phs.weill.cornell.edu/directory/profiles/jacky-choi) | Integrating the Redcap API with R <br> CONSORT flow diagrams in R | `R` <br> `R`|[<i class="fas fa-desktop fa-lg"></i>](https://simmwill.github.io/wcmbcc_pres_redcap) [<i class="fas fa-play fa-lg"></i>](https://wcm.box.com/s/23lknovcbkosdu16v5bfj3i033c6fuma) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2021/202106_Choi_CONSORT.pdf)| <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2021/202106_Choi_CONSORT.Rmd) |<br> [<i class="fab fa-safari fa-lg"></i>](https://dannyjnwong.github.io/STROBE-CONSORT-Diagrams-in-R/) [<i class="fab fa-safari fa-lg"></i>](https://scriptsandstatistics.wordpress.com/2017/12/22/how-to-draw-a-consort-flow-diagram-using-r-and-graphviz/)|
| 05/25/2021 1 -- 2pm | [Nicholas Williams, MPH](https://github.com/nt-williams) | An Introduction to Julia programming | `Julia` | | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2021/202105_Williams_Julia.html)  | |
| 04/27/2021 12 -- 1pm | [Daniel D. Sjoberg, MA](http://www.danieldsjoberg.com) | Presentation-ready Summary Tables with \{gtsummary\} | `R` | [<i class="fas fa-desktop fa-lg"></i>](http://www.danieldsjoberg.com/gtsummary-weill-cornell-presentation/#1)  [<i class="fas fa-play fa-lg"></i>](https://wcm.box.com/s/xihvceexbdowfp6a4b3h917e1nioebda) || [<i class="fab fa-safari fa-lg"></i>](https://github.com/ddsjoberg/gtsummary) |
| 01/19/2021 12 -- 1pm | [Katherine Hoffman, MS](https://www.khstats.com) | Become a Superlearner! An Introduction to Ensemble Learning with R | `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2021/202101_Hoffman_Superlearner.pdf) [<i class="fas fa-play fa-lg"></i>](https://wcm.box.com/s/x9mxbwud72zb2ccs0t9a748ywosev4fv) | [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/2021/202101_Hoffman_Superlearner.Rmd) | [<i class="fab fa-safari fa-lg"></i>](https://www.khstats.com/blog/sl/superlearning/) [<i class="fab fa-safari fa-lg"></i>](https://github.com/hoffmakl/causal-inference-visual-guides/blob/master/visual-guides/Superlearner.pdf) |

# 2020

| Date      | Presenter  | Topic  | Software | Slides | Code | Resources  |                                         
|:----------|:----------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|:--------------:|:-----------------------:|:------------:|:-------------------:|
| 07/14/2020 12 -- 1pm | [Nicholas Williams, MPH](https://github.com/nt-williams) | An Introduction to Answering Causal Questions with the `lmtp` Package | `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2020/202007_Williams_lmtp.pdf) [<i class="fas fa-play fa-lg"></i>](https://wcm.box.com/s/p85nud4otefc11ee8y8cqlof9tyxqm2m) | [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/2020/202007_Williams_lmtp.zip)  | [<i class="fab fa-safari fa-lg"></i>](https://towardsdatascience.com/an-introduction-to-estimating-the-causal-effects-of-feasible-interventions-e07ed45136ff) |
| 03/03/2020 12 -- 1pm | Attendees of R Studio | Takeaways from R Studio 2020 | `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2020/202003_Wu_rstudioconf.pdf)| [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/2020/202003_An_rstudioconf.R) | [<i class="fab fa-safari fa-lg"></i>](https://github.com/ianmcook/tidyquery) [<i class="fab fa-safari fa-lg"></i>](https://resources.rstudio.com/rstudio-conf-2020/one-r-markdown-document-fourteen-demosyihui-xie) |
| 02/19/2020 12 -- 1pm | <strong>Python Study Group</strong> | Functions | `Python` | | | |
| 01/28/2020 12 -- 1pm | <strong>Python Study Group</strong> | Variables, Expressions, and Statements | `Python` | | | |

# 2019

| Date      | Presenter  | Topic  | Software | Slides | Code | Resources  |                                         
|:----------|:----------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|:--------------:|:-----------------------:|:------------:|:-------------------:|
| 12/17/2019 12 -- 1pm | <strong>Python Study Group</strong> | Troubleshooting Installations <br> Introduction to study group | `Python` | | | |
| 12/03/2019 12 -- 1pm |  [Yiyuan Wu, MS](https://phs.weill.cornell.edu/directory/profiles/wu-yiyuan) <br> [Xiaoyue Ma, MSc](https://phs.weill.cornell.edu/directory/profiles/xiaoyue-ma) | DC R Conference Recap || [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201912_Wu_DC_R_Recap.pdf) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201912_Ma_DC_R_Recap.pdf)| |  [<i class="fab fa-safari fa-lg"></i>](file_resources/CheatSheet.pdf)
| 11/05/2019 1 -- 2pm | [Anjile An, MPH](https://phs.weill.cornell.edu/directory/profiles/anjile) <br> [Nicholas Williams, MPH](https://github.com/nt-williams)  | Making Better Scientific Posters with InDesign <br> `cabinets`: Project Specific Workspace Organization Templates | `InDesign` <br><br> `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201911_An_InDesign_Slides.pdf) <br> | <br>  [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2019/201911_Williams_cabinets_demo.R) | [<i class="fa fa-file-pdf-o fa-lg"></i>](file_slides/2019/201911_An_InDesign_Tutorial.pdf) [<i class="fa fa-file fa-lg"></i>](file_slides/2019/201911_An_InDesign_Poster_Template.indd)
| 10/15/2019 12 -- 1pm | [Oleksandr Savenkov, PhD](https://vivo.weill.cornell.edu/display/cwid-ols2010) | HPC Cluster |  | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201910_Savenkov_HPC_Cluster.html)  |  |
| 09/03/2019 12 -- 1pm | Attendees of JSM | Takeaways from JSM 2019 | |  |   | [<i class="fab fa-safari fa-lg"></i>](https://ww2.amstat.org/meetings/jsm/2019/) |
| 08/21/2019 12 -- 1pm | [Elizabeth Sweeney, ScM, PhD](https://emsweene.github.io) | Plotting the trail with `plotly` |`R` |  |   | [<i class="fab fa-safari fa-lg"></i>](https://github.com/emsweene/Plotly_Tutorial)   |
| 08/13/2019 12 -- 1pm | [Nicholas Williams, MPH](https://github.com/nt-williams) <br> [Katherine Hoffman, MS](https://www.khstats.com) | How to be a contributeR <br> Introduction to writing your own power calculation simulations in R | `R` <br> `R` | <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201908_Hoffman_Power_Simulations.pdf)  | <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2019/201908_Hoffman_Power_Simulations.R)   |   |
| 07/02/2019 12 -- 1pm | [Yiyuan Wu, MS](https://phs.weill.cornell.edu/directory/profiles/wu-yiyuan) <br> Victoria Cooley, MS | Overview of the `dygraphs` package <br> Overview of the `lubridate` package | `R` <br> `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201907_Wu_dygraphs.pdf) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201907_Cooley_lubridate.html) | [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2019/201907_Wu_dygraphs_examples.html) <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2019/201907_Cooley_lubridate.Rmd)   |  <br> [<i class="fab fa-safari fa-lg"></i>](https://evoldyn.gitlab.io/evomics-2018/ref-sheets/R_lubridate.pdf) |
| 07/24/2019 12 -- 1pm | [Anjile An, MPH](https://phs.weill.cornell.edu/directory/profiles/anjile) | Introduction to Adobe Illustrator for Scientists  | `Adobe Illustrator` |  |   | [<i class="fab fa-safari fa-lg"></i>](https://www.adobe.com/products/illustrator/free-trial-download.html) [<i class="fab fa-safari fa-lg"></i>](http://tinyurl.com/k8ya4gk)  |
| 07/16/2019 12 -- 1pm | Imaani Easthausen, MS | Intro to `tidymodels` | `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201907_Easthausen_Intro_to_Tidymodels.html)  |   |   |
| 06/18/2019 12 -- 1pm | Elizabeth Mauer, MS | Parameterized Reports  | `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201906_Mauer_Parameterized_Reports.html) | [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/2019/201906_Mauer_Parameterized_Reports_wine_ratings.Rmd) [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/2019/201906_Mauer_Parameterized_Reports_world_countries.Rmd) [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/2019/201906_Mauer_Parameterized_Reports_render_params.R)| [<i class="fab fa-safari fa-lg"></i>](https://bookdown.org/yihui/rmarkdown/parameterized-reports.html) [<i class="fab fa-safari fa-lg"></i>](https://docs.rstudio.com/connect/user/param-rmarkdown.html) [<i class="fab fa-safari fa-lg"></i>](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-05-28)   |   |
| 06/04/2019 11am -- 12pm | [Katherine Hoffman, MS](https://www.khstats.com) | R Projects, the `here` package, and other tips from the NYC R Conference  | `R`  | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201906_Hoffman_NYC_R_here.pdf) | [<i class="fa fa-file-code-o  fa-lg"></i>](https://github.com/hoffmakl/Rproj-here-tutorial) | [<i class="fa fa-file-code-o  fa-lg"></i>](https://github.com/hoffmakl/nyr-conf-comp-club) [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/2019/201906_Hoffman_NYC_R_here.html)  |
| 05/23/2019 Thursday 12 -- 1pm | [Xiaoyue Ma, MSc](https://phs.weill.cornell.edu/directory/profiles/xiaoyue-ma) <br> Kaylee Ho, MS | Creating plots in SAS <br> Nested data / list column workflow using purrr | `SAS` <br> `R`  | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201905_Ma_SAS_Plotting.pdf) | [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2019/201905_Ma_SAS_Plotting_Code.sas) [<i class="fa fa-file-excel-o fa-lg"></i>](file_slides/2019/201905_Ma_SAS_Plotting_Data.zip) <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2019/201905_Ho_purrr_demo.Rmd)  |   <br> [<i class="fab fa-safari fa-lg"></i>](https://aosmith.rbind.io/2018/08/20/automating-exploratory-plots/) [<i class="fab fa-safari fa-lg"></i>](https://hookedondata.org/going-off-the-map/) | 
| 05/09/2019 Thursday 12 -- 1pm | [Alan Wu, MS](https://phs.weill.cornell.edu/directory/profiles/wu-alan) | An introduction to Regex in R | `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201905_Wu_Intro_to_Regex.pdf) | [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/2019/201905_Wu_Intro_to_Regex.R)  |   |
| 04/23/2019 12 -- 1pm |  Gulce Askin, MPH <br> Hanhan Wang, MPS | R templates for consultation <br> Apply functions and Purrr  | `R` <br> `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201904_Askin_R_Templates.html) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201904_Wang_Functionals_in_R.html) | <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2019/201904_Wang_Functionals_in_R.Rmd) | [<i class="fab fa-safari fa-lg"></i>](http://ismayc.github.io/ecots2k16/template_pkg/) |
| 04/02/2019 12 -- 1pm | Victoria Cooley, MS <br> Kaylee Ho, MS | Visualization in R <br> GIS / Geospatial analysis (Supp) | `R` <br> `R` |  [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201904_Cooley_Visualization_in_R.html) | [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/2019/201904_Cooley_Visualization_in_R.Rmd) <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2019/201904_Ho_geospatial_demo_2.Rmd) | [<i class="fa fa-file-pdf-o fa-lg"></i>](file_slides/2019/201904_Cooley_colorPaletteCheatsheet.pdf) <br> [<i class="fa fa-file-pdf-o fa-lg"></i>](file_slides/2019/201904_Ho_kahle-wickham_ggmap.pdf) [<i class="fa fa-file-excel-o fa-lg"></i>](file_slides/2019/201904_Ho_addresses.csv) |
| 03/19/2019 12 -- 1pm | Kaylee Ho, MS <br> Xian Wu, MPH | GIS / Geospatial analysis <br> Applying propensity score methods to complex surveys  | `R` <br> `SAS` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201903_Ho_Intro_to_geospatial_analysis.pdf) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201903_Wu_Propensity_score.pdf) | [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2019/201903_Ho_geospatial_demo.Rmd) | [<i class="fa fa-file fa-lg"></i>](file_slides/2019/201903_Ho_geospatial_demo.html) |
| 03/05/2019 12 -- 1pm | [Katherine Hoffman, MS](https://www.khstats.com) | Overview of dplyr  | `R`  | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201903_Hoffman_dplyr.html) |   |   |
| 01/31/2019 4 -- 5pm | Clara Oromendia, MS | R Shiny | `R`  | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201901_Oromendia_R_Shiny.pdf) | [<i class="fa fa-file-code-o fa-lg"></i>](https://github.com/Oromendia/ShinyWorkshop2019)   | [<i class="fab fa-safari fa-lg"></i>](https://resources.rstudio.com/rstudio-conf-2019) [<i class="fab fa-safari fa-lg"></i>](https://github.com/rstudio/rstudio-conf/tree/master/2019)|
| 01/17/2019 4 -- 5pm | [Jihui Lee, PhD](https://jihuilee.com) | How to build a package in R | `R` |  [<i class="fas fa-desktop fa-lg"></i>](file_slides/2019/201901_Lee_R_Package.pdf) | [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/2019/201901_Lee_R_Package.R) | [<i class="fab fa-safari fa-lg"></i>](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/) [<i class="fab fa-safari fa-lg"></i>](https://support.rstudio.com/hc/en-us/articles/200486488-Developing-Packages-with-RStudio) |



# 2018

| Date      | Presenter  | Topic  | Software | Slides | Code | Resources  |                                         
|:----------|:----------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|:--------------:|:-----------------------:|:------------:|:-------------------:|
| 12/13/2018 4 -- 5pm | Elizabeth Mauer, MS | Workflow and organization for collaboration | | [<i class="fas fa-desktop fa-lg"></i>](file_slides/2018/201812_Mauer_Organization_and_Documentation_of_Workflow.html) [<i class="fas fa-desktop fa-lg"></i>](file_slides/2018/201812_Mauer_Integrating_Git_into_Your_Data_Analysis_Workflow_for_Version_Control.html) | | [<i class="fab fa-safari fa-lg"></i>](http://happygitwithr.com/)  [<i class="fa fa-file-pdf-o fa-lg"></i>](file_slides/2018/201812_Mauer_CodebookCookbook.pdf)|


