---
title: "Resources"
output:
  html_document:
    toc: true
    toc_float: true
---

## WCM-specific resources:

- Submit a CTSC consult [[link]](http://ctsc.med.cornell.edu/BiostatisticsConsult)
- RMarkdown reporting template by Nick Williams [[link]](https://github.com/nt-williams/wcmtheme)
- Communicating with a Statistician by Debby D'Angelo and Anjile An [[link]](file_resources/2022_DAngelo_An_communicating_with_statistician.pdf)

## Generally useful resources & links:

### R

- R packages [[link]](https://r-pkgs.org/)
- R Studio cheatsheets [[link]](https://resources.rstudio.com/rstudio-cheatsheets)
- htmlwidgets: Visualization in R [[link]](https://www.htmlwidgets.org/showcase_leaflet.html)
- The Beauty of ggplot2 by Jihui Lee [[pdf]](file_resources/Lee_R_ggplot2.pdf) [[html]](file_resources/Lee_R_ggplot2.html)
- Web-scraping with R [[link]](https://deepak915.github.io/post-1.html)


### Python

- Web-scraping with Python [[link]](https://deepak915.github.io/post-2.html)
- Hackerrank [[link]](https://www.hackerrank.com/domains/python)
- Book: Automate the boring stuff [[link]](https://automatetheboringstuff.com/)
- Book: Learn Python the hard way [[link]](https://learntocodetogether.com/learn-python-the-hard-way-free-ebook-download/)

### Blogs

- Kat Hoffman [[link]](https://www.khstats.com/)
- Emily Robinson [[link]](https://hookedondata.org/)
- David Robinson [[link]](http://varianceexplained.org/)
- Ken Jee [[link]](https://www.playingnumbers.com/)
- Paul Adamson [[link]](http://padamson.github.io/)
- Nicholas Tierney [[link]](https://njtierney.github.io/)



