---
title: "Schedule"
output:
  html_document:
    toc: true
    toc_float: true
---

<br>

Unless otherwise noted, we meet bi-weekly; Tuesdays at 12pm -- 1pm in C1. 

If there are topics you'd like (us) to cover, please let us know!

<br>

## Presentations

<br>
The first meeting of a month will be one 1-hour presentation by one presenter on a single topic. There will be interactive computing practice.

| Date      | Presenter  | Topic  | Software | Slides | Codes | Resources  |                                         
|:----------|:----------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------|:--------------:|:-----------------------:|:------------:|:-------------------:|
| 12/13/2018 4 -- 5pm | [Elizabeth Mauer, MS](http://hpr.weill.cornell.edu/divisions/biostatistics/Elizabeth_Mauer.html) | Workflow and organization for collaboration | | [<i class="fas fa-desktop fa-lg"></i>](file_slides/201812_Mauer_Organization_and_Documentation_of_Workflow.html) [<i class="fas fa-desktop fa-lg"></i>](file_slides/201812_Mauer_Integrating_Git_into_Your_Data_Analysis_Workflow_for_Version_Control.html) | | [<i class="fab fa-safari fa-lg"></i>](http://happygitwithr.com/)  [<i class="fa fa-file-pdf-o fa-lg"></i>](file_slides/201812_Mauer_CodebookCookbook.pdf)|
| 01/17/2019 4 -- 5pm | [Jihui Lee, PhD](https://jihuilee.com) | How to build a package in R | `R` |  [<i class="fas fa-desktop fa-lg"></i>](file_slides/201901_Lee_R_Package.pdf) | [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/201901_Lee_R_Package.R) | [<i class="fab fa-safari fa-lg"></i>](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/) [<i class="fab fa-safari fa-lg"></i>](https://support.rstudio.com/hc/en-us/articles/200486488-Developing-Packages-with-RStudio) |
| 01/31/2019 4 -- 5pm | [Clara Oromendia, MS](http://hpr.weill.cornell.edu/divisions/biostatistics/Clara_Oromendia.html) | R Shiny | `R`  | [<i class="fas fa-desktop fa-lg"></i>](file_slides/201901_Oromendia_R_Shiny.pptx) | [<i class="fa fa-file-code-o fa-lg"></i>](https://github.com/Oromendia/ShinyWorkshop2019)   | [<i class="fab fa-safari fa-lg"></i>](https://resources.rstudio.com/rstudio-conf-2019) [<i class="fab fa-safari fa-lg"></i>](https://github.com/rstudio/rstudio-conf/tree/master/2019)|
| 03/05/2019 12 -- 1pm | [Katherine Hoffman, MS](https://www.khstats.com) | Overview of dplyr  | `R`  | [<i class="fas fa-desktop fa-lg"></i>](file_slides/201903_Hoffman_dplyr.html) |   |   |
| 04/02/2019 12 -- 1pm | Victoria Cooley, MS | Visualization in R  | `R`  |  [<i class="fas fa-desktop fa-lg"></i>](file_slides/201904_Cooley_Visualization_in_R.html) | [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/201904_Cooley_Visualization_in_R.Rmd) | [<i class="fa fa-file-pdf-o fa-lg"></i>](file_slides/201904_Cooley_colorPaletteCheatsheet.pdf)  |
| 05/09/2019 **Thursday** 12 -- 1pm | Alan Wu, MS | An introduction to Regex in R | `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/An Intro to Regex in R.pptx) | [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/Regex intro.R)  |   |
| 06/04/2019 11am -- 12pm | [Katherine Hoffman, MS](https://www.khstats.com) | R Projects, the 'here' package, and other tips from the NYC R Conference  | `R`  | [<i class="fas fa-desktop fa-lg"></i>](file_slides/Rproject_here_slides.pdf) | [<i class="fab fa-safari fa-lg"></i>](https://github.com/hoffmakl/Rproj-here-tutorial) [<i class="fab fa-safari fa-lg"></i>](https://github.com/hoffmakl/nyr-conf-comp-club) | [<i class="fa fa-file-code-o  fa-lg"></i>](file_slides/nyc-r-highlights.html)  |
| 06/18/2019 12 -- 1pm | [Elizabeth Mauer, MS](http://hpr.weill.cornell.edu/divisions/biostatistics/Elizabeth_Mauer.html) | Parameterized Reports | `R` |  |   |   |
| 07/16/2019 12 -- 1pm | Imaani Easthausen, MS |  | |  |   |   |
| 08/20/2019 12 -- 1pm | |  | |  |   |   |

<br>

## Mini Presentations

<br>
The second meeting of a month will be mini presentations. Each presenter will introduce fun, new coding skills.
(e.g. visualization, reporting, new packages)

| Date      | Presenter  | Topic  | Software | Slides | Codes | Resources  |                                         
|:----------|:----------------------------------------------------------------|:--------------------------------------------------------------------------------------------------|:--------------:|:-----------------------:|:------------:|:-------------------:|
| 03/19/2019 12 -- 1pm |  Kaylee Ho, MS <br> [Xian Wu, MPH](http://hpr.weill.cornell.edu/divisions/biostatistics/Xian_Wu.html) | GIS / Geospatial analysis <br> Applying propensity score methods to complex surveys  | `R` <br> `SAS` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/201903_Ho_Intro_to_geospatial_analysis.pdf) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/201903_Wu_Propensity_score.pdf) | [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/201903_Ho_geospatial_demo.Rmd) | [<i class="fa fa-file fa-lg"></i>](file_slides/201903_Ho_geospatial_demo.html) |
| 04/02/2019 12 -- 1pm |  Kaylee Ho, MS | GIS / Geospatial analysis (Supp) | `R` |  | [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/201904_Ho_geospatial_demo_2.Rmd) | [<i class="fa fa-file-pdf-o fa-lg"></i>](file_slides/201904_Ho_kahle-wickham_ggmap.pdf) [<i class="fa fa-file-excel-o fa-lg"></i>](file_slides/201904_Ho_addresses.csv)
| 04/23/2019 12 -- 1pm |  [Gulce Askin, MPH](http://hpr.weill.cornell.edu/divisions/biostatistics/Gulce_Askin_profile.html) <br> [Hanhan Wang, MPS](http://hpr.weill.cornell.edu/divisions/biostatistics/Hanhan_Wang.html) | R templates for consultation <br> Apply functions and Purrr  | `R` <br> `R` | [<i class="fas fa-desktop fa-lg"></i>](file_slides/201904_Askin_R_Templates.html) <br> [<i class="fas fa-desktop fa-lg"></i>](file_slides/201904_Wang_Functionals_in_R.html) | <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/201904_Wang_Functionals_in_R.Rmd) | [<i class="fab fa-safari fa-lg"></i>](http://ismayc.github.io/ecots2k16/template_pkg/) |
| 05/23/2019 **Thursday** 12 -- 1pm | Xiaoyue Ma, MSc <br> Kaylee Ho, MS | Creating plots in SAS <br> Nested data / list column workflow using purrr | `SAS` <br> `R`  | [<i class="fas fa-desktop fa-lg"></i>](file_slides/201905_Ma_SAS_plot.pptx) | [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/201905_Ma_SAS_Code.sas) [<i class="fa fa-file-excel-o fa-lg"></i>](file_slides/201905_Ma_Data.zip) <br> [<i class="fa fa-file-code-o fa-lg"></i>](file_slides/201905_Ho_purrr_demo.Rmd)  |   <br> [<i class="fab fa-safari fa-lg"></i>](https://aosmith.rbind.io/2018/08/20/automating-exploratory-plots/) [<i class="fab fa-safari fa-lg"></i>](https://hookedondata.org/going-off-the-map/) | 
| 07/02/2019 12 -- 1pm | Yiyuan Wu, MS <br> Victoria Cooley, MS | TBD <br> TBD | `R` <br> `R` |  |   |   |
| 08/06/2019 12 -- 1pm | |  | |  |   |   |


